# name: CI - Lint, Test, Build

# on:
#   push:
#   pull_request:

# jobs:
#   lint:
#     name: CI Lint
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Modules
#         run: npm ci
#       - name: ESLint
#         env:
#           CI: true
#         run: npm run lint

#   test:
#     name: CI Tests
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install Modules
#       run: npm ci
#     - name: Run Tests
#       run: npm run test
