name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: CD Build Android
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install 
          cd ./android
          ./gradlew clean
          ./gradlew assembleRelease --warning-mode=all
      - uses: actions/upload-artifact@master
        with:
          name: apk
          path: ./android/app/build/outputs/apk/release/app-release.apk


  generate-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get file name
        id: name
        run: echo "::set-output name=file_name::fga-eps-mds-2021-2-Cartografia-social-front-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H-%M')-${{ github.event.release.tag_name }}"

      - name: Copy repository
        uses: actions/checkout@v2
      - run: mkdir -p /tmp/sonar/
      - run: curl --location --request POST  $METRICS_URL > /tmp/sonar/${{ steps.name.outputs.file_name }}.json
        env:
          METRICS_URL: ${{ secrets.METRICS_URL }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.name.outputs.file_name }}.json
          path: /tmp/sonar/${{ steps.name.outputs.file_name }}.json
      - name: Download APK File
        uses: actions/download-artifact@master
        with:
          name: apk
          path: ./
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *.apk
            LICENSE
            /tmp/sonar/${{ steps.name.outputs.file_name }}.json

      - name: Send metrics to docs repo
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
        with:
          source_file: /tmp/sonar/${{ steps.name.outputs.file_name }}.json
          destination_repo: 'fga-eps-mds/2021.2-Cartografia-social-front'
          destination_folder: 'analytics-raw-data/2021-2-Cartografia-social-front'
          user_email: ${{ secrets.GIT_EMAIL}}
          user_name: ${{ secrets.GIT_USER }}
          commit_message: New metrics from ${{ github.event.repository.name }}
